library(dplyr)
activities<-read.table("UCI HAR Dataset/activity_labels.txt",col.names = c("code", "activity"))
features<-read.table("UCI HAR Dataset/features.txt", col.names = c("n","functions"))
ytrain<-read.table("UCI HAR Dataset/train/y_train.txt",col.names = "codes")
xtrain<-read.table("UCI HAR Dataset/train/X_train.txt",col.names = features$functions)
subjecttrain<-read.table("UCI HAR Dataset/train/subject_train.txt",col.names = "subject")
ytest<-read.table("UCI HAR Dataset/test/y_test.txt",col.names = "codes")
xtest<-read.table("UCI HAR Dataset/test/X_test.txt",col.names = features$functions)
subjecttest<-read.table("UCI HAR Dataset/test/subject_test.txt",col.names = "subject")
x<-rbind(xtrain,xtest)
y<-rbind(ytrain,ytest)
subject<-rbind(subjecttrain,subjecttest)
mergedata<-cbind(subject,y,x)
cleandata<-mergedata %>% select(subject,codes,contains("mean"),contains("std"))
names(cleandata)<-gsub("Acc","Accelerometer",names(cleandata))
names(cleandata)<-gsub("Gyro","Gyroscope",names(cleandata))
names(cleandata)<-gsub("BodyBody","Body",names(cleandata))
names(cleandata)<-gsub("Mag","Magnitude",names(cleandata))
names(cleandata)<-gsub("^t","Time",names(cleandata))
names(cleandata)<-gsub("^f","Frequency",names(cleandata))
names(cleandata)<-gsub("tBody","TimeBody",names(cleandata))
names(cleandata)[2]="activity"
cleandata2<-cleandata %>%
        group_by(subject, activity) %>%
        summarise_all(list(mean))
write.table(cleandata2,"cleandata2.txt",row.name=FALSE)
